In [1]:
import numpy as np

Решение 1-ого примера

In [21]:
A=np.matrix(([1,2,4],[7,5,-2],[-2,1,3]))
B=np.matrix(([-1,0,3],[2,-6,1],[-7,1,5]))
C=np.matrix(([-2,3],[4,0],[7,-1]))

print(A+B,'\n')
print(B-A,'\n')
print(A*C,'\n')
print(A*B*C)

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]] 

[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]] 

[[34 -1]
 [-8 23]
 [29 -9]] 

[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [22]:
A=np.matrix(([0,3,4],[-7,1,-2],[2,-1,3]))
B=np.matrix(([1,2,4],[7,0,-2],[-3,-2,5]))
C=np.matrix(([-3,2],[0,4],[-1,7]))

print(A+B,'\n')
print(B-A,'\n')
print(A*C,'\n')
print(A*B*C)

[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]] 

[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]] 

[[ -4  40]
 [ 23 -24]
 [ -9  21]] 

[[ -41   84]
 [  22 -308]
 [  17  139]]
